services:
  msarts-app:
    build: .
    container_name: msarts-app
    restart: always
    volumes:
      - ./public:/app/public # Mapeia a pasta local da VM para dentro do container
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.msarts.rule=Host(`msarts.routerkencarv.duckdns.org`)"
      - "traefik.http.routers.msarts.entrypoints=websecure"
      - "traefik.http.routers.msarts.tls.certresolver=myresolver"
      - "traefik.http.services.msarts.loadbalancer.server.port=3000"
    environment:
      - PORT=3000
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
    networks:
      - traefik

networks:
  traefik:
    external: true
