services:
  msarts-app:
    build: .
    container_name: msarts-app
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.msarts.rule=Host(`seu-dominio.com.br`)"
      - "traefik.http.routers.msarts.entrypoints=websecure"
      - "traefik.http.routers.msarts.tls.certresolver=myresolver"
      - "traefik.http.services.msarts.loadbalancer.server.port=3000"
    environment:
      - PORT=3000
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
    networks:
      - traefik-proxy

networks:
  traefik-proxy:
    external: true
